### PR TITLE
Add OpenAI

### PR DESCRIPTION
**Pull request by in4margaret**

### CODE REVIEW

**Comment by tvenhaus** [comment]
In addition to creating the OpenAI service, should we also create a model deployment?  We would need to decide which model we want to use.

**Comment by Izzzu** [comment]
> In addition to creating the OpenAI service, should we also create a model deployment? We would need to decide which model we want to use.
> 
> Region Availability is a consideration: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#model-summary-table-and-region-availability

Good point, let's merge this one and add it in the next PR

**Review by Izzzu — APPROVED** [review]

**Comment by Izzzu** [comment]
As discussed: we can also add a make command to deploy the ai related infrastructure (similar way like main-obs)

**Comment by Izzzu** [comment]
> In addition to creating the OpenAI service, should we also create a model deployment? We would need to decide which model we want to use.
> 
> Region Availability is a consideration: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#model-summary-table-and-region-availability

I would go with the cheapest that is available in most of the regions for simplicity, this chat agent doesn't need to be super smart, it's just for demonstration purposes

**Pull request merged**
